name: demo

on:
  push:
    branches:
      - main

jobs:
  demo:
    name: demo
    runs-on: ubuntu-20.04

    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          whoami
          ls -al
